trigger:
  branches:
    include:
      - main
  paths:
    include:
      - src/BillIssue.App/**
      - src/pipelines/azure-app-pipeline.yml

pool:
  name: 'local-agents'

variables:
  NODE_VERSION: '20'

stages:
  - stage: Build
    displayName: 'Build React App'
    jobs:
      - job: Build
        displayName: 'Install & Build'
        steps:
          # Install Node.js 20
          - task: UseNode@1
            inputs:
              version: '$(NODE_VERSION)'
              
          - script: |
              echo "REACT_APP_API_URL=$(REACT_APP_API_URL)" > src/BillIssue.App/.env
            displayName: 'Write .env file'
            env:
              REACT_APP_API_URL: $(REACT_APP_API_URL)

          # Build React app
          - script: |
              cd src/BillIssue.App
              npm install
              npm run build
            displayName: 'Build React app'

          # Publish build artifacts
          - task: PublishPipelineArtifact@1
            inputs:
              targetPath: 'src/BillIssue.App/build'
              artifact: 'react-app-build'
              publishLocation: 'pipeline'

  - stage: Deploy
    displayName: 'Deploy to Azure App Service'
    dependsOn: Build
    jobs:
      - job: Deploy
        displayName: 'Deploy React App'
        steps:
          # Download build artifact
          - task: DownloadPipelineArtifact@2
            inputs:
              artifact: 'react-app-build'
              path: '$(Pipeline.Workspace)/build'

          # Deploy to Azure App Service
          - task: AzureWebApp@1
            inputs:
              azureSubscription: '$(AZURE_SERVICE_CONNECTION)'
              appType: 'webAppLinux'        # Change to 'webApp' if Windows
              appName: '$(AZURE_APP_NAME)'
              resourceGroupName: '$(AZURE_RESOURCE_GROUP)'
              package: '$(Pipeline.Workspace)/build'